### ISSUE TITLE
Standard title separator should be `;`

### ISSUE THREAD

**Issue by demery** [DigitalScriptorium/ds-data#10]
Change the titles separator for `authorized_label` and `standard_title` to `;`. Otherwise, the splits don't match when the record is read. All fields are split on `|`. 

Note:

```csv
as_recorded                           | authorized_label
-------------------------------------------------------------------
Liber metaphisice ; Liber ethicorum   | Metaphysics|Nicomachean Ethics
```

**Comment by demery** [comment]
I've fixed this in my local copy.

**Comment by lpcoladangelo** [comment]
Fixed in repo and documentation moving forward.
